#!/usr/bin/env bash
# AI Code Review — calls Groq API to analyze PR diff
# Reads: diff, SPECS.md, SKILLS.md, static-review results
# Writes: /tmp/review-comment.md
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$REPO_ROOT"

GROQ_API_KEY="${GROQ_API_KEY:?Missing GROQ_API_KEY}"
STATIC_REVIEW="${1:-/tmp/static-review.md}"

# ── 1. Get diff ──
DIFF_STAT=$(git diff main...HEAD --stat 2>/dev/null || git diff HEAD~1 --stat)
DIFF_FULL=$(git diff main...HEAD 2>/dev/null || git diff HEAD~1)

# Truncate diff if too large (Groq context limit ~30k tokens)
MAX_DIFF=12000
if [ ${#DIFF_FULL} -gt $MAX_DIFF ]; then
  DIFF_FULL="${DIFF_FULL:0:$MAX_DIFF}

[truncated — original was ${#DIFF_FULL} chars]"
fi

# ── 2. Read project specs ──
SPECS=""
if [ -f ".agent/SPECS.md" ]; then
  SPECS=$(head -c 8000 .agent/SPECS.md)
fi
SKILLS=""
if [ -f ".agent/SKILLS.md" ]; then
  SKILLS=$(head -c 4000 .agent/SKILLS.md)
fi

# ── 3. Read static review ──
STATIC_CONTENT=""
if [ -f "$STATIC_REVIEW" ]; then
  STATIC_CONTENT=$(cat "$STATIC_REVIEW")
fi

# ── 4. Build prompt ──
PROMPT=$(cat <<PROMPT_EOF
You are a code reviewer for a veterinary SaaS platform (Veterinaria V2).

PROJECT RULES (from SPECS.md):
${SPECS}

CODE CONVENTIONS (from SKILLS.md):
${SKILLS}

STATIC REVIEW RESULTS:
${STATIC_CONTENT}

GIT DIFF:
\`\`\`diff
${DIFF_FULL}
\`\`\`

Analyze the diff and static review results. Check for:
1. Architecture violations (Clean Architecture, Feature-Sliced Design)
2. Security issues (hardcoded secrets, injection, exposed endpoints)
3. Logic bugs or anti-patterns
4. Missing error handling
5. Convention violations (UUIDv7, soft-delete, RLS, naming)
6. Dependency issues (unnecessary or missing)
7. Migration safety (destructive operations)
8. Test adequacy

Respond in SPANISH. Format as markdown with these sections:
### ✅ Aprobado (lo que está bien)
### ⚠️ Advertencias (cosas a mejorar)
### ❌ Errores (cosas que se deben corregir)
### 💡 Sugerencias (mejoras opcionales)

### Veredicto: PASS o FAIL (si hay errores críticos)
PROMPT_EOF
)

# ── 5. Call Groq API ──
RESPONSE=$(curl -s https://api.groq.com/openai/v1/chat/completions \
  -H "Authorization: Bearer ${GROQ_API_KEY}" \
  -H "Content-Type: application/json" \
  -d "$(jq -n \
    --arg model "llama-3.3-70b-versatile" \
    --arg prompt "$PROMPT" \
    '{
      model: $model,
      messages: [{role: "user", content: $prompt}],
      temperature: 0.3,
      max_tokens: 2000
    }')")

AI_CONTENT=$(echo "$RESPONSE" | jq -r '.choices[0].message.content // "Error: No response from AI"')

# ── 6. Build final comment ──
{
  echo "## 🤖 Code Review — AI Agent"
  echo ""
  if [ -f "$STATIC_REVIEW" ]; then
    cat "$STATIC_REVIEW"
  fi
  echo ""
  echo "## 🧠 AI Analysis"
  echo ""
  echo "$AI_CONTENT"
  echo ""
  echo "---"
  echo "*Generated by code-review-agent · Model: llama-3.3-70b-versatile via Groq*"
} > /tmp/review-comment.md

echo "Review comment written to /tmp/review-comment.md"
