services:
  core_db:
    ports: []

  community_db:
    ports: []

  redis:
    ports: []

  rabbitmq:
    ports: []

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4001:8000"
    volumes: []
    env_file:
      - .env
    depends_on:
      core_db:
        condition: service_healthy
      community_db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend.prod
    # No ports - Nginx sirve los archivos estaticos
    # Copia los archivos a /opt/veter.v2/frontend/dist/ en el host
    volumes:
      - /opt/veter.v2/frontend/dist:/app/dist
