services:
  core_db:
    ports: []

  community_db:
    ports: []

  redis:
    ports: []

  rabbitmq:
    ports: []

  caddy:
    volumes:
      - ./infra/Caddyfile.prod:/etc/caddy/Caddyfile
      - caddy_data:/data
      - frontend_dist:/www
    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_completed_successfully

  backend:
    ports: []
    volumes: []
    env_file:
      - .env

  frontend:
    ports: []
    volumes:
      - frontend_dist:/app/dist
